# CUDA_VISIBLE_DEVICES=7 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/stable-diffusion-v1-4 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_4 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --negative_token --num_cpu 16 --num_gpu 1 --num_runs 100 --seed 3407 > SD1_4.log 2>&1 &
# CUDA_VISIBLE_DEVICES=7 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/stable-diffusion-v1-4 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_4 --dataset_root /dev/shm/alexJiang/eval_dataset/small_200_30_20_10/ --negative_token --num_cpu 16 --num_gpu 1 --num_runs 2 --seed 3407 > SD1_4.log 2>&1 &

# CUDA_VISIBLE_DEVICES=6 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/stable-cascade --output_dir /dev/shm/alexJiang/output/DiffDisEval/stable-cascade --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run > SC.log 2>&1 &
# CUDA_VISIBLE_DEVICES=5 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/stable-diffusion-v1-4 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_4 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run > SD1_4_single_run.log 2>&1 &
# CUDA_VISIBLE_DEVICES=5 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/stable-cascade --output_dir /dev/shm/alexJiang/output/DiffDisEval/stable-cascade --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --single_image --all_masks > SC_debug.log 2>&1 &
# CUDA_VISIBLE_DEVICES=5 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/stable-cascade --output_dir /dev/shm/alexJiang/output/DiffDisEval/stable-cascade --dataset_root /dev/shm/alexJiang/eval_dataset/small_200_30_20_10/ --seed 3407 --single_run --all_masks > SC_debug.log 2>&1 &
# CUDA_VISIBLE_DEVICES=6 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/stable-cascade --output_dir /run/alexJiang/output/DiffDisEval/stable-cascade --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --all_masks > SC_single_run.log 2>&1 &
# CUDA_VISIBLE_DEVICES=7 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/stable-cascade --output_dir /run/alexJiang/output/DiffDisEval/stable-cascade --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --num_cpu 24 --num_gpu 1 --num_runs 10 --all_masks > SC.log 2>&1 &

# CUDA_VISIBLE_DEVICES=6 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/stable-cascade --output_dir /dev/shm/alexJiang/output/DiffDisEval/stable-cascade --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --num_cpu 16 --num_gpu 1 --num_runs 100 --seed 3407 > SC.log 2>&1 &

# CUDA_VISIBLE_DEVICES=5 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/openjourney --output_dir /dev/shm/alexJiang/output/DiffDisEval/openjourney --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --negative_token --num_runs 25 --num_cpu 16 --num_gpu 2 > Openjourney.log 2>&1 &

# CUDA_VISIBLE_DEVICES=0 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/openjourney --output_dir /dev/shm/alexJiang/output/DiffDisEval/openjourney --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 12.0 --beta 0.5 > Openjourney_single_run_1.log 2>&1 &
# CUDA_VISIBLE_DEVICES=1 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/openjourney --output_dir /dev/shm/alexJiang/output/DiffDisEval/openjourney --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 13.0 --beta 0.5 > Openjourney_single_run_2.log 2>&1 &
# CUDA_VISIBLE_DEVICES=2 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/openjourney --output_dir /dev/shm/alexJiang/output/DiffDisEval/openjourney --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 14.0 --beta 0.5 > Openjourney_single_run_3.log 2>&1 &
# CUDA_VISIBLE_DEVICES=3 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/openjourney --output_dir /dev/shm/alexJiang/output/DiffDisEval/openjourney --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 15.0 --beta 0.5 > Openjourney_single_run_4.log 2>&1 &
# CUDA_VISIBLE_DEVICES=4 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/openjourney --output_dir /dev/shm/alexJiang/output/DiffDisEval/openjourney --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 > Openjourney_single_run_5.log 2>&1 &
# CUDA_VISIBLE_DEVICES=5 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/openjourney --output_dir /dev/shm/alexJiang/output/DiffDisEval/openjourney --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 11.0 --beta 0.5 > Openjourney_single_run_6.log 2>&1 &

# CUDA_VISIBLE_DEVICES=6 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/stable-cascade --output_dir /run/alexJiang/output/DiffDisEval/stable-cascade --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --all_masks --t 100 --neg_weight 0.0 --alpha_prior 8.0 --beta_prior 0.55 > SC_single_run_2.log 2>&1 &

# CUDA_VISIBLE_DEVICES=7 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/openjourney --output_dir /dev/shm/alexJiang/output/DiffDisEval/openjourney_debug --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --single_image --t 100 --alpha 8.0 --beta 0.5 > Openjourney_debug.log 2>&1 &
# CUDA_VISIBLE_DEVICES=7 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/openjourney --output_dir /dev/shm/alexJiang/output/DiffDisEval/openjourney --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --all_masks --t 100 --alpha 16.0 --beta 0.5 > Openjourney.log 2>&1 &

# CUDA_VISIBLE_DEVICES=5 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/openjourney --output_dir /dev/shm/alexJiang/output/DiffDisEval/openjourney --dataset_root /dev/shm/alexJiang/eval_dataset/small_200_30_20_10/ --seed 3407 --num_runs 100 --num_cpu 16 --num_gpu 1 > Openjourney_small_3_5_1_1.log 2>&1 &

# CUDA_VISIBLE_DEVICES=6 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_4 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_4 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --all_masks --t 100 --alpha 16 --beta 0.5 > SD1_4_2.log 2>&1 &
# CUDA_VISIBLE_DEVICES=7 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_5 --output_dir /run/alexJiang/output/DiffDisEval/SD1_5 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --all_masks --t 100 --alpha 16.0 --beta 0.5 > SD1_5_2.log 2>&1 &

# CUDA_VISIBLE_DEVICES=4 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/openjourney --output_dir /run/alexJiang/output/DiffDisEval/openjourney --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 108 --alpha 17.45 --beta 0.52 --neg_weight 0.243 > Openjourney_single_run.log 2>&1 &

# CUDA_VISIBLE_DEVICES=4 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_5 --output_dir /run/alexJiang/output/DiffDisEval/SD1_5 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 1.0 > SD1_5_single_run.log 2>&1 &
# CUDA_VISIBLE_DEVICES=5 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_5 --output_dir /run/alexJiang/output/DiffDisEval/SD1_5 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 1.0 --lr_flip > SD1_5_single_run_2.log 2>&1 &
# CUDA_VISIBLE_DEVICES=6 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_5 --output_dir /run/alexJiang/output/DiffDisEval/SD1_5 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 1.0 --ud_flip > SD1_5_single_run_3.log 2>&1 &
# CUDA_VISIBLE_DEVICES=7 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_5 --output_dir /run/alexJiang/output/DiffDisEval/SD1_5 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 1.0 --lr_flip --ud_flip > SD1_5_single_run_4.log 2>&1 &

# CUDA_VISIBLE_DEVICES=0 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_5 --output_dir /run/alexJiang/output/DiffDisEval/SD1_5 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 0.5 > SD1_5_robustness.log 2>&1 &
# CUDA_VISIBLE_DEVICES=1 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_5 --output_dir /run/alexJiang/output/DiffDisEval/SD1_5 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 0.5 --center_cropping > SD1_5_robustness_cc.log 2>&1 &
# CUDA_VISIBLE_DEVICES=2 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_5 --output_dir /run/alexJiang/output/DiffDisEval/SD1_5 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 0.5 --lr_flip > SD1_5_robustness_lr.log 2>&1 &

# CUDA_VISIBLE_DEVICES=0 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_4 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_4 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 1.0 > SD1_4_single_run.log 2>&1 &
# CUDA_VISIBLE_DEVICES=1 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_4 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_4 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 1.0 --lr_flip > SD1_4_single_run_2.log 2>&1 &
# CUDA_VISIBLE_DEVICES=2 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_4 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_4 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 1.0 --ud_flip > SD1_4_single_run_3.log 2>&1 &
# CUDA_VISIBLE_DEVICES=3 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_4 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_4 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 1.0 --lr_flip --ud_flip > SD1_4_single_run_4.log 2>&1 &

# CUDA_VISIBLE_DEVICES=3 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_4 --output_dir /run/alexJiang/output/DiffDisEval/SD1_4 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 0.5 > SD1_4_robustness.log 2>&1 &
# CUDA_VISIBLE_DEVICES=4 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_4 --output_dir /run/alexJiang/output/DiffDisEval/SD1_4 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 0.5 --center_cropping > SD1_4_robustness_cc.log 2>&1 &
# CUDA_VISIBLE_DEVICES=5 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_4 --output_dir /run/alexJiang/output/DiffDisEval/SD1_4 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 0.5 --lr_flip > SD1_4_robustness_lr.log 2>&1 &

# CUDA_VISIBLE_DEVICES=0 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD2_1 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD2_1 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 1.0 > SD2_1_single_run.log 2>&1 &
# CUDA_VISIBLE_DEVICES=1 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD2_1 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD2_1 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 1.0 --lr_flip > SD2_1_single_run_2.log 2>&1 &
# CUDA_VISIBLE_DEVICES=2 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD2_1 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD2_1 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 1.0 --ud_flip > SD2_1_single_run_3.log 2>&1 &
# CUDA_VISIBLE_DEVICES=3 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD2_1 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD2_1 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 1.0 --lr_flip --ud_flip > SD2_1_single_run_4.log 2>&1 &

# CUDA_VISIBLE_DEVICES=6 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD2_1 --output_dir /run/alexJiang/output/DiffDisEval/SD2_1 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 0.5 > SD2_1_robustness.log 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD2_1 --output_dir /run/alexJiang/output/DiffDisEval/SD2_1 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 0.5 --center_cropping > SD2_1_robustness_cc.log 2>&1 &&
CUDA_VISIBLE_DEVICES=7 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD2_1 --output_dir /run/alexJiang/output/DiffDisEval/SD2_1 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 0.5 --lr_flip > SD2_1_robustness_lr.log 2>&1 &

# CUDA_VISIBLE_DEVICES=0 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD2_1 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD2_1/ablation_1/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 91 --alpha 8.0 --beta 0.4 --map_weight1 0.19 --map_weight2 0.47 --map_weight3 0.19 --map_weight4 0.15 --neg_weight 0.0 > SD2_1_single_run_ablation_1.log 2>&1 &
# CUDA_VISIBLE_DEVICES=1 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD2_1 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD2_1/ablation_2/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 91 --alpha 8.0 --beta 0.4 --map_weight1 0.19 --map_weight2 0.47 --map_weight3 0.19 --map_weight4 0.15 --neg_weight 0.0 --augmented_label > SD2_1_single_run_ablation_2.log 2>&1 &
# CUDA_VISIBLE_DEVICES=2 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD2_1 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD2_1/ablation_3/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 91 --alpha 8.0 --beta 0.4 --map_weight1 0.19 --map_weight2 0.47 --map_weight3 0.19 --map_weight4 0.15 --neg_weight 0.1 --augmented_label > SD2_1_single_run_ablation_3.log 2>&1 &
# CUDA_VISIBLE_DEVICES=3 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD2_1 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD2_1/ablation_4/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 91 --alpha 8.0 --beta 0.4 --map_weight1 0.19 --map_weight2 0.47 --map_weight3 0.19 --map_weight4 0.15 --neg_weight 1.0 --augmented_label > SD2_1_single_run_ablation_4.log 2>&1 &

# CUDA_VISIBLE_DEVICES=3 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_4 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_4/ablation_1/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --map_weight1 0.3 --map_weight2 0.5 --map_weight3 0.1 --map_weight4 0.1 --neg_weight 0.0 > SD1_4_single_run_ablation_1.log 2>&1 &
# CUDA_VISIBLE_DEVICES=4 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_4 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_4/ablation_2/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --map_weight1 0.3 --map_weight2 0.5 --map_weight3 0.1 --map_weight4 0.1 --neg_weight 0.0 --augmented_label > SD1_4_single_run_ablation_2.log 2>&1 &
# CUDA_VISIBLE_DEVICES=5 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_4 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_4/ablation_3/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --map_weight1 0.3 --map_weight2 0.5 --map_weight3 0.1 --map_weight4 0.1 --neg_weight 0.1 --augmented_label > SD1_4_single_run_ablation_3.log 2>&1 &
# CUDA_VISIBLE_DEVICES=6 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_4 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_4/ablation_4/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --map_weight1 0.3 --map_weight2 0.5 --map_weight3 0.1 --map_weight4 0.1 --neg_weight 0.2 --augmented_label > SD1_4_single_run_ablation_4.log 2>&1 &
# CUDA_VISIBLE_DEVICES=7 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_4 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_4/ablation_5/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --map_weight1 0.3 --map_weight2 0.5 --map_weight3 0.1 --map_weight4 0.1 --neg_weight 0.3 --augmented_label > SD1_4_single_run_ablation_5.log 2>&1 &

# CUDA_VISIBLE_DEVICES=1 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_5 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_5/ablation_1/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --map_weight1 0.3 --map_weight2 0.5 --map_weight3 0.1 --map_weight4 0.1 --neg_weight 0.0 > SD1_5_single_run_ablation_1.log 2>&1 &
# CUDA_VISIBLE_DEVICES=2 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_5 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_5/ablation_2/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --map_weight1 0.3 --map_weight2 0.5 --map_weight3 0.1 --map_weight4 0.1 --neg_weight 0.0 --augmented_label > SD1_5_single_run_ablation_2.log 2>&1 &
# CUDA_VISIBLE_DEVICES=0 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_5 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_5/ablation_3/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --map_weight1 0.3 --map_weight2 0.5 --map_weight3 0.1 --map_weight4 0.1 --neg_weight 0.1 --augmented_label > SD1_5_single_run_ablation_3.log 2>&1 &
# CUDA_VISIBLE_DEVICES=2 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_5 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_5/ablation_4/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --map_weight1 0.3 --map_weight2 0.5 --map_weight3 0.1 --map_weight4 0.1 --neg_weight 0.2 --augmented_label > SD1_5_single_run_ablation_4.log 2>&1 &
# CUDA_VISIBLE_DEVICES=7 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_5 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_5/ablation_5/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --map_weight1 0.3 --map_weight2 0.5 --map_weight3 0.1 --map_weight4 0.1 --neg_weight 0.3 --augmented_label > SD1_5_single_run_ablation_5.log 2>&1 &

# CUDA_VISIBLE_DEVICES=0 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/openjourney --output_dir /dev/shm/alexJiang/output/DiffDisEval/openjourney/ablation_1/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --map_weight1 0.3 --map_weight2 0.5 --map_weight3 0.1 --map_weight4 0.1 --neg_weight 0.0 > Openjourney_single_run_ablation_1.log 2>&1 &
# CUDA_VISIBLE_DEVICES=0 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/openjourney --output_dir /dev/shm/alexJiang/output/DiffDisEval/openjourney/ablation_2/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --map_weight1 0.3 --map_weight2 0.5 --map_weight3 0.1 --map_weight4 0.1 --neg_weight 0.0 --augmented_label > Openjourney_single_run_ablation_2.log 2>&1 &
# CUDA_VISIBLE_DEVICES=1 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/openjourney --output_dir /dev/shm/alexJiang/output/DiffDisEval/openjourney/ablation_3/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --map_weight1 0.3 --map_weight2 0.5 --map_weight3 0.1 --map_weight4 0.1 --neg_weight 0.1 --augmented_label > Openjourney_single_run_ablation_3.log 2>&1 &
# CUDA_VISIBLE_DEVICES=1 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/openjourney --output_dir /dev/shm/alexJiang/output/DiffDisEval/openjourney/ablation_4/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --map_weight1 0.3 --map_weight2 0.5 --map_weight3 0.1 --map_weight4 0.1 --neg_weight 0.2 --augmented_label > Openjourney_single_run_ablation_4.log 2>&1 &
# CUDA_VISIBLE_DEVICES=6 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/openjourney --output_dir /dev/shm/alexJiang/output/DiffDisEval/openjourney/ablation_5/ --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --map_weight1 0.3 --map_weight2 0.5 --map_weight3 0.1 --map_weight4 0.1 --neg_weight 0.3 --augmented_label > Openjourney_single_run_ablation_5.log 2>&1 &


# CUDA_VISIBLE_DEVICES=1 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_4 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_4 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 0.0 > SD1_4_single_run_.log 2>&1 &
# CUDA_VISIBLE_DEVICES=2 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/SD1_5 --output_dir /dev/shm/alexJiang/output/DiffDisEval/SD1_5 --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16.0 --beta 0.5 --neg_weight 0.0 > SD1_5_single_run_DiffDisEval.log 2>&1 &
# CUDA_VISIBLE_DEVICES=3 nohup python -u main_benchmark.py --diffusion_model /dev/shm/alexJiang/source/openjourney --output_dir /dev/shm/alexJiang/output/DiffDisEval/openjourney --dataset_root /dev/shm/alexJiang/eval_dataset/large_500_300_150_50/ --seed 3407 --single_run --t 100 --alpha 16 --beta 0.5 --neg_weight 0.0 > Openjourney_single_run_DiffDisEval.log 2>&1 &



